name: Trigger auto deployment for archseapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/archseapp-AutoDeployTrigger-ca3ca28b-ce98-4e6a-93ba-77c1b5301943.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARCHSEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARCHSEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARCHSEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ARCHSEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARCHSEAPP_REGISTRY_PASSWORD }}
          containerAppName: archseapp
          resourceGroup: MCTResourceGroup
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


